### ISSUE TITLE
A API /animal PUT permite cadastrar dados inválidos

### ISSUE THREAD

**Issue by Kirmayrtomaz** [Ajuda-Manaus/api-adotaeu#6]
Ao atualizar os dados de um animal na requisição PUT /animal/:id está ocorrendo os erros parecidos da issues  #2  #3 #4.
- [ ]  Erro parecido da issue #2  
- [ ]  Erro parecido da issue #3  
- [ ]  Erro parecido da issue #4  

De formas que temos que analisar qual será a forma que a api aceitara a atualização dos dados. Existem algumas formas como:
- Enviando somente os campos que vão ser atualizados
- Enviando todos os campos do modelo, com os atualizados e não atualizados
